using DecompilerApp.Application;
using DecompilerApp.Decompilation;
using DecompilerApp.Export;
using DecompilerApp.Host;
using DecompilerApp.UI;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Photino.Blazor;

var builder = PhotinoBlazorAppBuilder.CreateDefault(args);
builder.Services.AddLogging(logging => logging.AddConsole());
builder.Services.AddSingleton<IDecompilerBackend, DecompilerBackend>();
builder.Services.AddSingleton<IProjectExportService, ProjectExportService>();
builder.Services.AddSingleton<WorkspaceState>();
builder.Services.AddSingleton<IFileDialogService, PhotinoFileDialogService>();
builder.Services.AddSingleton<IWorkspaceSessionService, WorkspaceSessionService>();
builder.RootComponents.Add<App>("app");
var app = builder.Build();
app.MainWindow.SetTitle("DnSpyXDX").SetIconFile(Path.Combine(AppContext.BaseDirectory, "wwwroot", "dnspyxdx.png")).SetSize(1320, 840).SetMinSize(860, 560).SetUseOsDefaultSize(false);
WindowStateManager.Attach(app.MainWindow);
app.Run();
